# Generated by Django 6.0.2 on 2026-02-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_lengkap", models.CharField(max_length=100)),
                ("jenis_kelamin", models.CharField(max_length=10)),
                ("tanggal_lahir", models.DateField()),
                ("alamat", models.CharField(max_length=225)),
                ("nomor_telepon", models.CharField(max_length=15)),
                ("nama_keluarga", models.CharField(max_length=100)),
                ("sudah_baptis", models.BooleanField(default=False)),
                ("sudah_sidi", models.BooleanField(default=False)),
                ("pelayanan_diikuti", models.CharField(blank=True, max_length=100)),
                ("ibadah_sering_diikuti", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
