# Generated by Django 6.0.2 on 2026-02-18 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keluarga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_keluarga", models.CharField(max_length=200)),
                ("alamat", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="member",
            name="alamat",
        ),
        migrations.RemoveField(
            model_name="member",
            name="nama_keluarga",
        ),
        migrations.AlterField(
            model_name="member",
            name="sudah_baptis",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="member",
            name="sudah_sidi",
            field=models.BooleanField(),
        ),
        migrations.AddField(
            model_name="member",
            name="keluarga",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="members.keluarga",
            ),
        ),
    ]
