# Generated by Django 6.0.2 on 2026-02-24 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_keluarga_remove_member_alamat_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perpuluhan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField()),
                ("jumlah", models.DecimalField(decimal_places=2, max_digits=10)),
                ("metode_pembayaran", models.CharField(max_length=50)),
                ("keterangan", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perpuluhan",
                        to="members.member",
                    ),
                ),
            ],
        ),
    ]
